### ISSUE TITLE
Global LoadingConfig

### ISSUE THREAD

**Issue by picosam** [Zak-C/ngx-loading#1]
Firstly, thank you, this is a life saver!
Is it possible to set the loading configuration (animation) globally so that we don't need to pass it every time we insert the loading directive into a component?

**Comment by Zak-C** [comment]
Hi @picosam 

No problem! 

I will try and add this functionality to the package in the coming days. 

Thanks

**Comment by Zak-C** [comment]
Hi @picosam 

The ability to define global configuration has now been added in the latest release (v1.0.3).
