### ISSUE TITLE
ngx-loading version 7.0.0  eedefineInjectable, eeinjectdefineInjectable

### ISSUE THREAD

**Issue by chris601** [Zak-C/ngx-loading#102]
Hi 

Your file ngx-loading.js version 7.0.0  imports eedefineInjectable, eeinjectdefineInjectable  this should be defineInjectable and injectdefineInjectable. this also needs updating throughout the file.

When corrected the library works.  This isn't ideal as it will break everytime the project is installed.

**Comment by lcroffi** [comment]
Found the exact same issue, we will have to use another loader.

**Comment by antrodart** [comment]
Same issue, I solved it automatically by replacing all the 'ɵ' chars programatically, in my patch.js file that I run before building the app.
```
const file_ngx_loading = 'node_modules/ngx-loading/fesm5/ngx-loading.js';

fs.readFile(file_ngx_loading, 'utf8', function (err, data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace(/ɵ/g, '');

  fs.writeFile(file_ngx_loading, result, 'utf8', function (err) {
    if (err) return console.log(err);
  });
});
```

**Comment by Zak-C** [comment]
Angular V7 is no longer supported.
