### ISSUE TITLE
Library not allowing loader

### ISSUE THREAD

**Issue by ietabhi** [Zak-C/ngx-loading#103]
Environment details:-

Library : Angular 7
ngx-loading : ^7.0.0
OS: Win
Node : 10x
Configurations : Webpack 4, UMD library

Angular library not allowing to use, i  m facing issue  : -

@NgModule({
  //...
  imports: [
    //...
    **NgxLoadingModule.forRoot({})**
  ],
  //...
})

Compilation failed Log: 

Error during template compile of 'NVTAppRootModule'
  Function calls are not supported in decorators 'NgxLoadingModule'

=============================================

When i use below code in library App not loading:-

@NgModule({
  //...
  imports: [
    //...
    **NgxLoadingModule**
  ],
  //...
})

Log details :-

ngx-loading.js:54 Uncaught TypeError: Object(...) is not a function
    at ngx-loading.js:54
    at Module../node_modules/ngx-loading/fesm5/ngx-loading.js (ngx-loading.js:56)
    at __webpack_require__ (bootstrap:63)

**Comment by lenichols** [comment]
Having the same issue.

**Comment by Zak-C** [comment]
Angular V7 is no longer supported.
