### ISSUE TITLE
Full screen backdrop isn't working in Edge

### ISSUE THREAD

**Issue by gerlis18** [Zak-C/ngx-loading#104]
Hey! I've found a little bug with **fullScreenBackdrop** option in Edge explorer, what happens is that backdrop appears but it doesn't fit to the screen like in Google Chrome.

Here is mi code:
```html
<ngx-loading [show]="true"
             [config]="{ backdropBorderRadius: '3px', fullScreenBackdrop: true}"
></ngx-loading>
```
**ngx-loading version:** ^3.0.1
**Angular version:** ~8.1.2
**Edge version:** 44

**Comment by diegodesouza** [comment]
Doesn't see like we're getting support on these =/

**Comment by gerlis18** [comment]
You're right, but we can figure out that errors and fix them.

**Comment by Zak-C** [comment]
Just tested this in later (supported) versions of the library and Edge and was not able to reproduce. Please re-open if this is still an issue
