### ISSUE TITLE
angular 9/10

### ISSUE THREAD

**Issue by capc0** [Zak-C/ngx-loading#109]
please create a new release with angular 9 as a peer dependency

**Comment by jerone** [comment]
I'm making an inventory to see if our project is possible to upgrade to Angular 9. According to the [installation instructions](https://github.com/Zak-C/ngx-loading#npm) it looks like `ngx-loading` is not ready. But an missing changelog or releases page is not confirming this. Only reference is this ticket.

@Zak-C My question, does `ngx-loading` work with Angular 9? Or will be updated in the foreseeable future?

**Comment by capc0** [comment]
I use this component in an angular 9 project and it works as intended. You will get deprecation warnings from npm though that you need angular 8 installed.

**Comment by jerone** [comment]
Ping @Zak-C 🏓

**Comment by ietabhi** [comment]
is there any plan to update current library,
it will be good if you add peerdeps as >= so no warning will be shown for projects

**Comment by andredesousa** [comment]
The next PR will update to Angular 10:

https://github.com/Zak-C/ngx-loading/pull/118

**Comment by alanorth** [comment]
We are also already using this on Angular 9.0. I was upgrading to Angular 9.1 and got this dependency error from npm:

```console
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^8.0.0" from ngx-loading@8.0.0
npm ERR! node_modules/ngx-loading
npm ERR!   ngx-loading@"^8.0.0" from the root project
```

I'm just going to fork it and bump the dependencies in `package.json` for now because the project clearly already works in Angular 9.

**Comment by Zak-C** [comment]
Closing as Angular version 9 is no longer supported. Version 13 of this package has since been released which supports Angular 13.
