### ISSUE TITLE
(inactive) backdrop blocks parts of my app

### ISSUE THREAD

**Issue by paddotk** [Zak-C/ngx-loading#112]
Hi,

Whenever the loader is not showing (`[show]="false"`), the backdrop still blocks everything because of its high z-index. I can't manage to override the z-index, and can only omit this issue by putting an *ngIf on the component which checks for the same value as the `[show]` does.

My component is as simple as this.
`<ngx-loading [show]="displayLoader" [config]="config"></ngx-loading>`

Preferrably, we'd have an option to disable the backdrop altogether. In my case this is unwanted anyway, and I made it transparent.

**Comment by Zak-C** [comment]
Hi, please can you show how this issue can be reproduced? The backdrop should not be present if show is not set to true.
