### ISSUE TITLE
Can't bind to 'show' since it isn't a known property of 'ngx-loading' on ng build --prod 

### ISSUE THREAD

**Issue by 11et401012** [Zak-C/ngx-loading#113]
ERROR in : Can't bind to 'show' since it isn't a known property of 'ngx-loading'.
1. If 'ngx-loading' is an Angular component and it has 'show' input, then verify that it is part of this module.
2. If 'ngx-loading' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("class="container" style="padding-top:20px;padding-bottom:60px;margin-top: 66px;">
    <ngx-loading [ERROR ->][show]="loading"></ngx-loading>
    <div class="row panel">
        <div class="col-md-12">
")
: 'ngx-loading' is not a known element:
1. If 'ngx-loading' is an Angular component, then verify that it is part of this module.
2. If 'ngx-loading' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("eader>
<div class="container" style="padding-top:20px;padding-bottom:60px;margin-top: 66px;">
    [ERROR ->]<ngx-loading [show]="loading"></ngx-loading>
    <div class="row panel">
        <div class="col-md")

**Comment by Zak-C** [comment]
@11et401012 Is this still an issue? If so can you specify which version you were using? Can you show how this can be reproduced?
