### ISSUE TITLE
cannot install in angular 10 - ModuleWithProviders missing option

### ISSUE THREAD

**Issue by waratah** [Zak-C/ngx-loading#117]
ERROR in node_modules/ngx-loading/lib/ngx-loading.module.d.ts:4:55 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

4     static forRoot(loadingConfig: INgxLoadingConfig): ModuleWithProviders;
                                                        ~~~~~~~~~~~~~~~~~~~

**Comment by waratah** [comment]
https://github.com/Zak-C/ngx-loading/pull/118

**Comment by Zak-C** [comment]
Closing as Angular version 10 is no longer supported. Version 13 of this package has since been released which supports Angular 13.
