### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by INGCRENGIFO** [Zak-C/ngx-loading#15]
Hi, it does not work for me. But I have a question.
I have the import in app.module, but the login I have in another module. I have to do the import also in login.module and the other modules where I use it?
I remove it from app.module?
I use lazy loading, is there a problem?

thanks

**Comment by Zak-C** [comment]
Hi @INGCRENGIFO, 

You can import the LoadingModule module into your app.module, where you can then call forRoot() to setup the default configuration (if required). 

If your app.module imports your login.module, then yes, you will need to make sure that your login.module also imports the LoadingModule (do not call forRoot() here). 

Thanks
