### ISSUE TITLE
Doesn't work with Server Side Rendering

### ISSUE THREAD

**Issue by mfrro** [Zak-C/ngx-loading#16]
Hi,
I'm currently trying to get my angular project to work with SSR. One of the modules that causes errors when used on the server is ngx-loading. I get several "Unexpected token export" and "Unexpected token import" errors. There is an issue regarding this problem at angular/angular-cli#7200. The verdict seems to be, that the modules causing the error have to be changed to conform to the angular package format. I'm not sure what that would mean for this package. It might be as simple as changing the tsconfig to compile to commonjs.

**Comment by Zak-C** [comment]
Hi @mfrro, 

Thank you for bringing this up. I will take a look through the thread and try to work on a fix for this. 

Thanks

**Comment by Zak-C** [comment]
Hi @mfrro,

I have updated the build process to follow the official Angular package format. The relevant changes are now in v1.0.8. 

Could you please give this a test and let me know if it resolves your issue? 

Thank you

**Comment by mfrro** [comment]
@Zak-C I'm not getting the error anymore, so the issue seems to have been resolved. Thanks a bunch for taking care of it so quickly!
