### ISSUE TITLE
Angular 16.0 -> https://github.com/Zak-C/ngx-loading/pull/168

### ISSUE THREAD

**Issue by theodury** [Zak-C/ngx-loading#167]
Hello, 

Could we have the version of the package with the version 16.0 ?

**Comment by theodury** [comment]
https://github.com/Zak-C/ngx-loading/pull/168/files

**Comment by theodury** [comment]
@Zak-C  could you give me the access to the pipeline please ? 
![image](https://github.com/Zak-C/ngx-loading/assets/6726393/b4603b24-9124-45e8-af3f-0926a1518915)

**Comment by daniela-rps** [comment]
Hi @Zak-C ,

Could you please give us an update on this? Thanks!

**Comment by ozkoidi** [comment]
@Zak-C, what is the status here? Any estimation on when this library will be Angular 16 compatible?

**Comment by SimonCorellia** [comment]
any news from @Zak-C ?

**Comment by LiveOrDevTrying** [comment]
Request to have this updated for angular 16

**Comment by LuanPiresBresolla** [comment]
i have the same problem, need to, need a version for angular 16

**Comment by tangamampilia** [comment]
@Zak-C any news?

**Comment by Zak-C** [comment]
V16 now supported.
