### ISSUE TITLE
Error installing dependencies on Linux

### ISSUE THREAD

**Issue by datencia** [Zak-C/ngx-loading#17]
Hi @Zak-C Great job!

I'm facing an issue on Linux. After cloning your repo, the `npm install` command fails due to the `COPY` command used to copy the `README.md` file into the `dist` folder.

The error is located under the `copyReadme` npm script command. See next screenshot.

![image](https://user-images.githubusercontent.com/18591213/31406397-810ad0ce-ae01-11e7-8b81-eaac86d6856d.png)

I will send a PR to fix it.

**Comment by Zak-C** [comment]
Hi @datencia, 

Thank you!

Thank you for the pull request, I appreciate it. 

I have just released a new version of the package (v1.0.8), which I hope will resolve #16. Part of this change involved removing the 'COPY' script. I therefore hope that your issue should be resolved in v1.0.8. 

Could you please give it a try and let me know the verdict? 

Thank you

**Comment by datencia** [comment]
cool :1st_place_medal: 

Using [ng-packagr](https://github.com/dherges/ng-packagr) has fixed the issue.

I will close the issue (and the PR as well since it is no longer necessary).
