### ISSUE TITLE
Add support for Angular 17

### ISSUE THREAD

**Issue by shipengqi** [Zak-C/ngx-loading#171]
Now that Angular 17 has been released, are there any plans to release a new version that supports Angular 17?

**Comment by Zak-C** [comment]
Hi @shipengqi, I'm aiming to get on this in the next few days - will provide an update shortly.

**Comment by Zak-C** [comment]
https://github.com/Zak-C/ngx-loading/releases/tag/v17.0.0

17.0.0 now available: https://www.npmjs.com/package/ngx-loading/v/17.0.0
