### ISSUE TITLE
Loading on a large scrollable page 

### ISSUE THREAD

**Issue by Jalrom** [Zak-C/ngx-loading#2]
I have a page which is pretty long and if I scroll down the loading backdrop will not cover the bottom of my page. 
Here is my app.component.html
```html
<div>
  <ngx-loading [show]="globals.loading"></ngx-loading>
  <app-header></app-header>
  <div style="padding-top: 80px" class="fade-in main-client public">
    <router-outlet></router-outlet>
  </div>
  <app-footer></app-footer>
</div>
```
I think I may be doing something wrong.

**Comment by Jalrom** [comment]
Turns out I'm just bad at css. 
I needed to set the first divs position to relative.

**Comment by ahmet90** [comment]
Hi,How to resolve this issue ? I already have a problem with scrolling page
