### ISSUE TITLE
Adding Text to the loader or pic

### ISSUE THREAD

**Issue by masloord** [Zak-C/ngx-loading#24]
Is there a way to add a div of text or image to the loader?

**Comment by vhugogarcia** [comment]
I would like as well to add a text below or above the spinner animation, so we can show the user the process that is executing in that moment.

Any ideas?

**Comment by JoeHarstad** [comment]
@chadbr - It would be slick if we could drop in an ng-template.  Let me know when this is complete and I'll check this out.  For now, need to find something else.  Thx

**Comment by chadbr** [comment]
yea - I got nowhere on this - and haven't had time to follow up -- sorry...

**Comment by Zak-C** [comment]
Hi, 

I have released new versions of the library: v2.0.1 (for Angular 4 / 5 applications) and v3.0.1 for Angular 6 applications. 

This has now been resolved as part of these releases. Please check the documentation / StackBlitz demo for further information (use the new template input variable).
