### ISSUE TITLE
Can you add a Service instead of using [show]

### ISSUE THREAD

**Issue by ghiscoding** [Zak-C/ngx-loading#27]
Would it be possible to add a Service that I can inject in any of my components. I would like to declare a global spinner (in the App component) with global configuration and simply call a `spin()` method from a Spinner Service. 

The missing Service and option to change spinner size would be really awesome (that is mentioned in another open issue). 

Thanks for the lib :)

**Comment by crooksey** [comment]
Why don't you just create your own service that stores the value of loading, each component that needs to set or access ngx-loading can then call or update it, and pass it to its template. Or the parent component can subscribe to the result, any other component can update the value of the service, then ngx-loading will fire in the parent. 

This isn't really an issue directly related to ngx-loading, but more of an individual  app design.

**Comment by ghiscoding** [comment]
Sure I could create my own service to deal with this, but so does plenty of other users. If it was built in, then many users wouldn't have to create it separately every single time. It's just a feature request, but yes I know that I can create my own service and we're in business, but it would still be nice if it was built in.

**Comment by ghiscoding** [comment]
I'll close the issue since I got around this, so it's no longer required on my side. Thanks
