### ISSUE TITLE
Loading on a large scrollable page

### ISSUE THREAD

**Issue by ahmet90** [Zak-C/ngx-loading#3]
Hi, backDrop rectangle not expanding on scrolled page size.

**Comment by Serhatselim** [comment]
hi, i have same problem, please fix it.

**Comment by talynone** [comment]
I had the same problem, I fixed it by surrounding the ngx-loading tag with a div with a relative position of relative.

`<div style="position: relative;"><ngx-loading [show]="loading" [config]="{ backdropBorderRadius: '14px' }"></ngx-loading>`

**Comment by Serhatselim** [comment]
@talynone this way not fix my problem , because  not show transparent background than I dont want can pick page when page loading.

**Comment by richqez** [comment]
i have same problem

**Comment by Serhatselim** [comment]
.backdrop[_ngcontent-c1] {
                z-index: 50;
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                background-color: rgba(0, 0, 0, 0.3);
            }
@Zak-C solve problem

**Comment by Zak-C** [comment]
Hi, 

Sorry for the delay in getting back to you. 

I will take a look at this and try and get it resolved as soon as possible. 

Thanks

**Comment by Serhatselim** [comment]
@Serhatselim please apply this way fastly @Zak-C 

_Sent from my Gm GM 5 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Zak-C** [comment]
@Serhatselim @ahmet90 I have released a new version of the library - v1.0.7. 

This version allows you to set the 'fullScreenBackdrop' variable as part of the ngx-loading configuration settings. When set to true, the backdrop will cover the whole screen, and the selected animation will be in the center of the screen. 

Please let me know if this resolves your issue.

**Comment by Serhatselim** [comment]
@Zak-C thank u sir , we resolved our problem.

**Comment by vibhupuri** [comment]
@renecruzlaguna 
Here is a working excample 
 `<ngx-loading [show]="loading" [config]="{ backdropBorderRadius: '14px',fullScreenBackdrop:true }"></ngx-loading>`
Hope this helps.

**Comment by avinashjgtp10** [comment]
<ngx-loading [show]="loading"  [config]="{ backdropBorderRadius: '3px',fullScreenBackdrop:true }" ></ngx-loading>  using fullscreenbacdrop resolves problem
