### ISSUE TITLE
Problem when used in conjunction with ngx-leaflet

### ISSUE THREAD

**Issue by crooksey** [Zak-C/ngx-loading#30]
So I will stat by saying (and admitting) my css skills are not the best, so I am having trouble debugging the following issue.

Background: I have been using ngx-loading for the past 6 weeks and it works perfectly. However, as of today I started using leafletjs with the plugin [ngx-leaflet](https://github.com/Asymmetrik/ngx-leaflet).

Now this plugin works correctly within my application, and I have the following template that uses ngx-loading and ngx-leaflet:
```
<ngx-loading [show]="loading" [config]="{ backdropBorderRadius: '14px' }"></ngx-loading>
<div class="row">
    <div class="col-sm-12" *ngFor="let key of keys">
            <!-- my looped code here -->
    </div>
<!-- code below added which causes problem -->
    <div class="col-sm-12">
        <div style="height: 600px;"
            leaflet
            [leafletLayersControl]="layersControl"
            [leafletOptions]="options">
        </div>
    </div>
<!-- code above added which causes problem -->
</div>
```

Now as you can see from the above commented code, I have added code to my template which in essence renders an interactive openstreetmap viewer in my browser, and when I now inititate ngx-loading, the animation no longer comes to the top of the page.

See Fig1 below that shows ngx-loading working, before I added leafletjs code.
![Fig1](https://i.imgur.com/jujaP5N.png)

See Fig2 below that shows ngx-leaflet working, before I calling ngx-loading.
![Fig2](https://i.imgur.com/Pe0jmwg.png)

See Fig3 below that shows that when ngx-loading is called with ngx-leaflet, the animation seems to be "stuck" underneath the rendered map, I am sure this is just a css setting, but I have tried to play around with the style editor in firefox to fix this issue, and I can't seem to get anywhere, are there any likely tags that I need to add or remove to either ngx-loading or ngx-leaflets css to fix this?
![Fig3](https://i.imgur.com/A0ibVVK.png)

**Comment by Zak-C** [comment]
Hi @crooksey, 

I have released the code containing your pull request (#32). Please try ngx-loading v1.0.10, which should resolve this issue. 

Thanks
