### ISSUE TITLE
ngx-loading not working with Observable calls in Angular 5

### ISSUE THREAD

**Issue by ilivestrong** [Zak-C/ngx-loading#33]
Hi,

I have tried to use ng-loading in my angular 5 project. though it seems to work fine with Promise based calls, it doesn't work at all with Rxjs observable calls. No error is output on console either, and it just doesn't show up.

Any ideas guys?

Thanks in advance.

**Comment by Zak-C** [comment]
Hi @ilivestrong, 

Can you please provide a sample app / sample code? I have not experienced the issues you describe. 

Thanks

**Comment by Zak-C** [comment]
Closing as I believe that this is an implementation issue, rather than an issue with the library itself. Happy to reopen and look into this further if you can provide an example of the problem. 

Thanks

**Comment by ilivestrong** [comment]
@Zak-C  - Yes it was an implementation issue. Fixed now, working like a charm...

Cheers!
