### ISSUE TITLE
Can't bind to 'show' since it isn't a known property of 'ngx-loading'

### ISSUE THREAD

**Issue by kconfesor** [Zak-C/ngx-loading#4]
1. If 'ngx-loading' is an Angular component and it has 'show' input, then verify that it is part of this module.
2. If 'ngx-loading' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("editbutton]="true" [custombutton]="true" [fullscreenbutton]="true"  color="darken">
  <ngx-loading [ERROR ->][show]="loading" [config]="{ backdropBorderRadius: '14px' }"></ngx-loading>
  <header>
    <span cl"): ng:///AgencyModule/VisitsListComponent.html@1:15
Can't bind to 'config' since it isn't a known property of 'ngx-loading'.
1. If 'ngx-loading' is an Angular component and it has 'config' input, then verify that it is part of this module.
2. If 'ngx-loading' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by VitaliyKovtun** [comment]
The same error.

**Comment by Zak-C** [comment]
Hi, 

Can you please confirm what version of the package you are running? Can you provide steps to reproduce this issue? 

Thank you

**Comment by javidot** [comment]
I'm having the same error. I'm using version 1.0.5 with angular-cli 1.0.5. On the app.module I have this:
`    LoadingModule.forRoot({
        animationType: ANIMATION_TYPES.wanderingCubes,
        backdropBackgroundColour: 'rgba(0,0,0,0.1)',
        backdropBorderRadius: '4px',
        primaryColour: '#ffffff',
        secondaryColour: '#ffffff',
        tertiaryColour: '#ffffff'
    }),`
and then on another module I also import LoadingModule:
`@NgModule({
  imports: [
    ...
    LoadingModule
  ],`

**Comment by FreezingCode** [comment]
@kconfesor , @VitaliyKovtun  Are you using server side rendering in your app?
@Zak-C Does this app support server side rendering? I was about to try ngx-loading in my app, but this issue seems identical to errors I've received on other Angular 4 modules I've tried that don't support server side rendering (which my app uses).

**Comment by Zak-C** [comment]
@FreezingCode are you referring to Ahead-of-Time Compilation (AOT)? If so, that could potentially be the issue, as I have not verified that the library is AOT compatible. 

I will do some investigation and get back to you.

**Comment by Zak-C** [comment]
@FreezingCode I have done some investigation and can confirm that the library is compatible with AOT. 

I have created an AOT build of a sample application, which has ngx-loading as a dependency. The application builds and runs successfully. 

I am currently not able to reproduce this issue.

**Comment by Zak-C** [comment]
Closing as unable to reproduce and no responses have been received. 

Happy to revisit if someone can reproduce.

**Comment by xoapit** [comment]
It's the same as my problem, I have imported Loading module to both app.module and children module, but it still don't work

**Comment by nehatshephertz** [comment]
@xoapit , did you added in the import........i had the same issue and added "LoadingModule" in the appComponent "imports". Now it is working. 

Steps to add "LoadingModule" in angular project

1. In appComponent add the  import
import { LoadingModule } from 'ngx-loading';

2. In appComponent imports add "LoadingModule "

3. I had a child component of appComponent this "home", in homeComponent import "LoadingModule " again 

import { LoadingModule } from 'ngx-loading';

4. In home.component.html 
<ngx-loading [show]="loading" [config]="{ backdropBorderRadius: '14px' }"></ngx-loading>

**Comment by cyphercodes96** [comment]
@nehatshephertz  in app component imports?

I don't have any imports inside my appComponent.

Facing same issue while using phantomJS to test my pre-builds ( AOT )
  1. If 'ngx-loading' is an Angular component and it has 'show' input, then verify that it is part of this module.
        2. If 'ngx-loading' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("tent-style">
              <span *ngIf="isLoaded"><router-outlet></router-outlet></span>
              <ngx-loading [ERROR ->][show]="!isLoaded"></ngx-loading>
            </div>
          </div>

**Comment by adnan333bd** [comment]
> 
> 
> Hi,
> 
> I had the same issue (and error output in console) using angular-cli, i added LoadingModule into the root app module (eg. `/src/app/app.module.ts`) but i forgot to add it into the module of component were the tag was added (eg. `/src/app/components/login/login.module.ts`).
> So add it in your current component module file and it will work ;)

Author should update the readme file ...
