### ISSUE TITLE
Loader shows full-screen with fullScreenBackdrop: false

### ISSUE THREAD

**Issue by michaelByrne** [Zak-C/ngx-loading#42]
Usage:

`<ngx-loading [show]="loading" [config]="{ fullScreenBackdrop: false }"></ngx-loading>
`
Shows full-screen modal when, presumably, it should be limited to the component. Am I using this wrong?

**Comment by Zak-C** [comment]
Hi @michaelByrne,

Does the component that contains the ngx-loading element, have it's position CSS attribute set to 'relative'? This is required as per the documentation. 

Thanks

**Comment by michaelByrne** [comment]
Ah, there it is. Closing
