### ISSUE TITLE
this.loading = false; not work

### ISSUE THREAD

**Issue by viiny123** [Zak-C/ngx-loading#43]
Hello,
I'm setting the variable this.loading = false; but it is not working, the loading continues to be exported, what should I do besides set false to loading so that it stops being displayed?

if (confirm("Tem certeza que deseja excluir " + item.numFogo + " " +  item.fabricante + " " + item.modelo + "?")) {
      //setar true loadind
      this.loading = true;
      var index = this.rows.indexOf(item);
      this.rows.splice(index, 1);
      this.service
        .delete(item.pneuId)
        .subscribe(res => {
          //setar false... loadind
          this.loading = false;
          alert("ok");
        }, err => {
          alert("Não foi possível deletar o item.");
          this.rows.splice(index, 0, item);
          this.loading = false;
        });
    }

**Comment by Zak-C** [comment]
Hi @viiny123, 

I can't see an issue with the above code. Can you please show us the relevant HTML template? 

As long as you have pointed the 'loading' input parameter of the ngx-loading element to your 'loading' variable, then setting the 'loading' variable to false should be enough to dismiss the loading spinner. 

Have you verified that 'loading' is definitely being set to false? Can you log the value to the console to double check?  

Thanks

**Comment by Alchemik** [comment]
The problem may lies in fact that part of code where you're setting `loading` flag run outside of Angular's zone so it's not aware of change (you can read more on that [HERE](https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html))
Try to inport `NgZone` module and wrap your code like: 
```
this._ngZone.run(() => {
    this.loading = false;
}
```
