### ISSUE TITLE
Is it possible to use this with router resolver? 

### ISSUE THREAD

**Issue by uurtsaikhb** [Zak-C/ngx-loading#44]
Thank you for nice component and it's easy to use.

Want to display it with different view and close it in another view after router resolver completes? 

Thank you,

**Comment by Zak-C** [comment]
Hi @uurtsaikhb, 

I'm not sure if I understand your question. Could you please elaborate and perhaps provide and example? 

Thanks

**Comment by uurtsaikhb** [comment]
Hi @Zak-C  I was able to solve my problem creating service and storing loading in service. Closing this issue. 

Thank you,
