### ISSUE TITLE
Im trying to `this.loading = 'true';` when I click on onchange event. Not working properly

### ISSUE THREAD

**Issue by vinayistar** [Zak-C/ngx-loading#45]
When onchange function called I say `this.loading = 'true';` and when the switch case ends I say `this.loading = 'false';`. But it won't works till I gives timeout. Please suggest me some way.

**Comment by Zak-C** [comment]
@vinayistar can you please provide some sample code?

**Comment by Zak-C** [comment]
Closing. 

Happy to reopen if you are able to provide some example code.
