### ISSUE TITLE
Add [showError] input

### ISSUE THREAD

**Issue by Jiehong** [Zak-C/ngx-loading#46]
Hi,

Today, the loading component can be displayed or not. However, in case of a failed load for example, it would be nice to be able to be able to have a [showError] with its configuration to be able to show a different thing when in error occurred.

I was thinking about something like a sad face, or something similar:

![](https://thumb9.shutterstock.com/display_pic_with_logo/2210297/331463465/stock-vector-face-sign-icon-vector-illustration-flat-design-style-331463465.jpg)

This is a feature request, and not a bug report.

**Comment by Zak-C** [comment]
Hi @Jiehong, 

I feel that this is out of scope for this library. You could obviously implement this yourself in your client code if you wish. 

Thanks
