### ISSUE TITLE
failed to load resource error during instantiating of ngx-Loading

### ISSUE THREAD

**Issue by edilks** [Zak-C/ngx-loading#49]
I haven't even tried toggling the loading bool as yet.  I get the loading error with what I added below.  If I remove the code below, the app comes up fine.  Using Visual Studio i get the intelliSense enumerations on the ANIMATION_TYPES, so I know my paths are correct on the map statement.   Thanks for the help.

**systemjs.config.js:**
    map:
        ...
        'ngx-loading': 'npm:ngx-loading/bundles/ngx-loading.umd.js',

**app.module.ts:**
        import { LoadingModule, ANIMATION_TYPES } from 'ngx-loading';

@NgModule({
    imports: [
        AppRoutingModule,
        LoadingModule.forRoot({
            animationType: ANIMATION_TYPES.wanderingCubes,
            backdropBackgroundColour: 'rgba(0,0,0,0.1)',
            backdropBorderRadius: '4px',
            primaryColour: '#ffffff',
            secondaryColour: '#ffffff',
            tertiaryColour: '#ffffff'
        }) 

**app.component:**
    public loading = false

**app.component.html**
   <ngx-loading [show]="loading" [config]="{ backdropBorderRadius: '14px' }"></ngx-loading>

**Comment by Zak-C** [comment]
I can't immediately see any issues with your setup. Is this still an issue?
