### ISSUE TITLE
Not Working!!!

### ISSUE THREAD

**Issue by saketk6** [Zak-C/ngx-loading#5]
I have tried and applied every dependencies as described at :-  https://www.npmjs.com/package/ngx-loading

But i didn't understood what's with the CoreModule. i coudn't find that in my project or even in this git repository.

Do i have to do anything else than described at :- https://www.npmjs.com/package/ngx-loading.

Their is no error but it's not showing the animations while i hit the Login.
Please Help!!

**Comment by Zak-C** [comment]
Hi, 

You do not necessarily need the core module import. That is just a module that I use as part of the standard structure of my Angular projects. I will try to remove that line from the README. 

The instructions in the README should get you up and running. 

Please let me know is if you have any specific issues and I will try to help you out. 

Thanks

**Comment by ilivestrong** [comment]
It doesn't seem to work with Observable calls.
