### ISSUE TITLE
Externalize style part, and compress it.

### ISSUE THREAD

**Issue by dsuwirya** [Zak-C/ngx-loading#52]
Hi,

When I run the Google Lighthouse web performance analyzer, there're couple of improvement opportunities, which I believe to be related to style part of ngx-loading, as follow:

![image](https://user-images.githubusercontent.com/5710527/36329081-46438fa6-132a-11e8-8545-eb37012ffcb8.png)

Would it be possible to externalize it and compress it, so it will pass this analysis ?

Thanks.

**Comment by Zak-C** [comment]
Hi, 

I have released new versions of the library: v2.0.1 (for Angular 4 / 5 applications) and v3.0.1 for Angular 6 applications. 

I hope that this has now been resolved as part of these releases.
