### ISSUE TITLE
Why ILoadingConfig is not exported anymore?

### ISSUE THREAD

**Issue by swftvsn** [Zak-C/ngx-loading#55]
Hi, 

I'm trying to have multiple configurations that are selected runtime. Everything works OK, but I'd like to have the compiler complain if you later remove or change some configuration options. That is, I'm trying to do this:

```ts
import { ANIMATION_TYPES, ILoadingConfig } from 'ngx-loading'
```
And then later 
```ts
mainOverlayConfig: ILoadingConfig = {
  animationType: ANIMATION_TYPES.threeBounce,
  backdropBackgroundColour: 'rgba(0, 0, 0, 0.1)',
  backdropBorderRadius: '4px',
  primaryColour: '#ffffff',
  secondaryColour: '#ffffff',
  tertiaryColour: '#ffffff'
}

imageLoadingConfig: ILoadingConfig = {
  animationType: ANIMATION_TYPES.threeBounce,
  backdropBackgroundColour: 'rgba(255, 255, 255, 0)',
  backdropBorderRadius: '4px',
  primaryColour: 'rgba(0, 0, 0, 0.1)',
  secondaryColour: 'rgba(0, 0, 0, 0.1)',
  tertiaryColour: 'rgba(0, 0, 0, 0.1)'
}
```

and finally 
```html
<ngx-loading [show]="loadingImage" [config]="imageLoadingConfig"></ngx-loading>
```
What's the rationale in removing the exports in https://github.com/Zak-C/ngx-loading/commit/0b71780c7356481eab2f83bc00d69e3cfe3df3ca ? I can understand that the class is not exported, but the interface should be, right?

**Comment by Zak-C** [comment]
Hi, 

I have released new versions of the library: v2.0.1 (for Angular 4 / 5 applications) and v3.0.1 for Angular 6 applications. 

This has now been resolved as part of these releases.
