### ISSUE TITLE
Implementing font-size property

### ISSUE THREAD

**Issue by LucaSarge4** [Zak-C/ngx-loading#57]
Hi,
I want to add a new property in order to make spinner circleSwish size tunable. 

I forked your project and committed my changes but I can't build this module since some needed configuration files are missing. 

So I want to ask you if you can add that files (eg. tsconfig, angular-cli.json and so on) or, at least, if could you build your project with my commit and you can update the build on the official npm repository.

here is the commit that should be merged:
https://github.com/LucaSarge4/ngx-loading/commit/d2947c735ae2d99acef6c4a0c722eaa12f491143

**Comment by Zak-C** [comment]
Duplicate - #10
