### ISSUE TITLE
disable scroll on loading

### ISSUE THREAD

**Issue by mohammadjalili** [Zak-C/ngx-loading#58]
hi ,
i want to close scroll page when loading is shown.
how can I?
thx

**Comment by Zak-C** [comment]
Hi @mohammadjalili 

I'm not sure I understand what you are trying to achieve here, can you please provide a more in depth explanation?

Thanks

**Comment by mohammadjalili** [comment]
between start loading and finish loading how can i disabled scrolling on page?

**Comment by Zak-C** [comment]
You can look into using the fullScreenBackdrop property, which can be used to cover the whole page.
