### ISSUE TITLE
ngx-loading add label in black screen

### ISSUE THREAD

**Issue by DiegoVenancioVieira** [Zak-C/ngx-loading#61]
I'm using ngx-loading and working very well. I wanna know if is possible add labels in black screen. Something like image below:

![1](https://user-images.githubusercontent.com/27169911/41500728-cd041c26-716d-11e8-87c3-ad1ca29df4dc.jpg)

[Stackoverflow question](https://stackoverflow.com/q/50889786/4654957)

**Comment by Zak-C** [comment]
Duplicate - see #24.
