### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError with simple Observer setup

### ISSUE THREAD

**Issue by brunojcm** [Zak-C/ngx-loading#62]
I'm trying to use `ngx-loading` here with the following setup:

HTML:

```
<my-app>
<ngx-loading [show]="loadingMask" [config]="{ backdropBorderRadius: '2px' }"></ngx-loading>
```

TS:
```
export class AppComponent implements OnInit {

    public loadingMask: boolean = false;

    constructor(router: Router, private trackingService: TrackingService, private loadingService: LoadingService) {
        this.loadingService.getLoadingObservable().subscribe(newLoading => {
            this.loadingMask = newLoading;
        });

    }
    ngOnInit() {    }
}
```

On the first time the function passed to `subscribe` is called (only the first one) I get this message on the console:
```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'show: false'. Current value: 'show: true'.
    at viewDebugError (core.js:8445)
    at expressionChangedAfterItHasBeenCheckedError (core.js:8433)
    at checkBindingNoChanges (core.js:8535)
    at checkNoChangesNodeInline (core.js:11401)
    at checkNoChangesNode (core.js:11390)
    at debugCheckNoChangesNode (core.js:11997)
    at debugCheckDirectivesFn (core.js:11925)
    at Object.eval [as updateDirectives] (AppComponent.html:8)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11914)
    at checkNoChangesView (core.js:11289)
```

The mask works, though, and it keeps working with no issues as long as I tested.

This workaround "fixes" the error, but I can't really see what's wrong with the first version of my code:
```
export class AppComponent implements OnInit {

    public loadingMask: boolean = false;

    constructor(router: Router, private trackingService: TrackingService, private loadingService: LoadingService, cdRef: ChangeDetectorRef) {
        this.loadingService.getLoadingObservable().subscribe(newLoading => {
            console.log("Changing loadingMask to " + newLoading);
            this.loadingMask = newLoading;

            //
            cdRef.detectChanges();
        });
    }
    ngOnInit() {  }
}
```

Is there anything that can explain that?

**Comment by Zak-C** [comment]
Hi @brunojcm 

This error is not related to this package, and is instead caused by how change detection works in Angular. Please see this link for more information: https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4 

Out of interest, if you were to move your code that is inside your constructor into your ngOnInit method, does that help at all?

**Comment by brunojcm** [comment]
Hi, @Zak-C.

I had read this link before, you posted on another issue, but I don't think there is anything not compliant with angular best practices in the first approach of my code. The way to pass data from a parent component to a child one in via input, which is essencially what I'm doing in the code above. I've done that with hundreds of different components so far without receiving this message, so I can't really see what could be wrong.

Do you remind of anything out of the ordinary you had to use to make this component possible? That might lead us to understand what could be causing this issue.

> Out of interest, if you were to move your code that is inside your constructor into your ngOnInit method, does that help at all?

I tried that was well, but I get the same error.

**Comment by ryanbuening** [comment]
@brunojcm I'm having the same issue. What does your `LoadingService` look like? I'm trying to implement your workaround.

**Comment by ryanbuening** [comment]
@brunojcm thanks for the workaround. Worked for me as well. This issue has been bothering me for the past 6 months.

**Comment by brunojcm** [comment]
Looks like I'm not alone at all, we have someone else in StackOverflow with this exact same error:
https://stackoverflow.com/questions/46837438/angular2-expressionchangedafterithasbeencheckederror

**Comment by brunojcm** [comment]
I had a second look here, in more detail, and I understood what was happening.

In my case here, I have a view that, on the `ngInit()`, subscribe to a quite complex `combineLatest()` kind of observable, which most of the time happens to have all its source observers in memory, so the subscription is synchronous. In this subscription, I call some HTTP requests that end up triggering `this.loadingMask = true` in my code.

Checking the stacktrace, this component's `ngInit()` is being called indirectly by Angular's `detectChanges()`, which is pretty standard, no big deal here.

Given that circunstance, where are about to call `this.loadingMask = true`, which is going to set `show=true`, during a change detection cycle, by chance just after angular has already checked `show=false`, leading to the error described in this issue.

As I mentioned before, I see no theoretical mistake as far as Angular change detection is concerned, I'm not doing anything out of the extraordinary here, using `ngAfterViewInit()`, nor any other controversial practice, AFAICS, of course.

Being that said, and considering my previous workaround of doing `cdRef.detectChanges()` a little bit more aggressive than I'd like, follows my current workaround (Inspired by https://blog.angular-university.io/angular-debugging/):

```
export class AppComponent implements OnInit, OnDestroy {

    loadingSubscription: Subscription;
    public loadingMask: boolean = false;

    constructor(private loadingService: LoadingService) {
    }

    ngOnInit() {
        this.loadingSubscription = this.loadingService.getLoading$().subscribe(newLoading => {
            // workaround to https://github.com/Zak-C/ngx-loading/issues/62
            // prevents the loading component of being potentially updated during a change detection cycle
            setTimeout(() => {
                this.loadingMask = newLoading;
            });
        });
    }

    ngOnDestroy(): void {
        this.loadingSubscription.unsubscribe();
    }

}
```

@Zak-C I really think you should reconsider your position about this issue and provide a better way of dealing with this problem.

Changing the `show` input to have a setter and call the `cdRef.markForCheck()`, for example, would be a better approach. Even if you don't want the component do it itself, at least provide a public method allowing someone o call `markForCheck()` for your component indirectly.

What do you think?

**Comment by gatsbys** [comment]
Moving my Future to the ctor solved it!

**Comment by brunojcm** [comment]
Issue is not happening anymore with Angular 9/Ivy, so in the long run it should disappear anyway.
