### ISSUE TITLE
ngx-loading not loading through service in angular 5

### ISSUE THREAD

**Issue by nwoow** [Zak-C/ngx-loading#64]
I am trying to create a loading effect whenever I hit my service for which I am using ngx-loading module.

In my component I am adding this:

<div class="my-container">
   <ngx-loading [show]="loading" [config]="{ backdropBorderRadius: '14px' }"></ngx-loading>
 </div>
I can load this using this code inside my component using:

 this.loading = true;
But I want to use this inside my service I am triggering my service from my component.ts like:

this.SvgService.test(u,user.view,user.rain_fall_type,user.years,user.districts);
And in my service I am using this:

public loading = false;
test(a,views,rain_fall_type,year,districts) {
    let url = `${this.apiRoot}/rainfalls/test?views=` + views +'&rain_fall_type='+rain_fall_type+'&year='+year;   
console.log("true");
    // title;
    this.loading = true;
    var title = rain_fall_type;
    this.http.get(url).
    subscribe(res => {
    this.j = res;
    this.loading = false;
    if (districts == "All") {
        this.map_districts(this.j) 
    } else {
        this.map_bihar_vs_districts(districts)
    } 
    }
    );
}
This is not working how can I trigger loading inside my service.

**Comment by Zak-C** [comment]
Hi @nwoow 

If you point the element to your service, you should be good to go. 

E.g. `<ngx-loading [show]="SvgService.loading"></ngx-loading>
`
