### ISSUE TITLE
Using ngx-loading as a preloader

### ISSUE THREAD

**Issue by cyphercodes96** [Zak-C/ngx-loading#67]
can we simply add <ngx-loading [show]="true"></ngx-loading> in the index.html file?

**Comment by Zak-C** [comment]
Hi @cyphercodes96,

The component is designed to be used within Angular components, therefore I do not think that it will be possible to use the component as an application pre-loader, within index.html. 

Thanks

**Comment by cyphercodes96** [comment]
It actually worked

I did a rewrite of the ngx-loading component inside the index.html file
