### ISSUE TITLE
Overlay does not fill the entire screen

### ISSUE THREAD

**Issue by phoude** [Zak-C/ngx-loading#69]
If the spinner is shown after scrolling from a long page then only part of the screen shows the overlay.
See https://stackblitz.com/edit/angular-ngx-loading

**Comment by jayeshanandani** [comment]
Please see for solution here:

You can achieve it via fullScreenBackdrop mentioned at: https://github.com/Zak-C/ngx-loading#config-options

```
<ngx-loading [show]="loading" [config]="{ backdropBorderRadius: '14px',fullScreenBackdrop:true }"></ngx-loading>
```
