### ISSUE TITLE
Can change animationType to the image ?

### ISSUE THREAD

**Issue by wuttinanDEV** [Zak-C/ngx-loading#7]
by default animationType have four items : threeBounce,rotatingPlane,rectangleBounce,wanderingCubes but I would to change that animation by default to my image

**Comment by Zak-C** [comment]
Hi,

I have released new versions of the library: v2.0.1 (for Angular 4 / 5 applications) and v3.0.1 for Angular 6 applications.

This has now been resolved as part of these releases. Please check the documentation / StackBlitz demo for further information (use the new template input variable).
