### ISSUE TITLE
Example of the loading masks

### ISSUE THREAD

**Issue by PMabMI** [Zak-C/ngx-loading#70]
I had to make something to show the different options we had available for our design team and thought that maybe you'd wish to include it in the documentation to help out others (if there's already one I managed to miss it) that are wondering what each options looks like.

The coloring is:
Primary - Red
Secondary - Green
Tertiary - Blue

https://angular-hkhtox.stackblitz.io

**Comment by Zak-C** [comment]
Hi @PMabMI ,

Thank you very much for putting this together. 

I have recently released a new version of the library and used this post as inspiration for a demo, which is documented within the README.
