### ISSUE TITLE
Gallery of loading masks

### ISSUE THREAD

**Issue by Balagii** [Zak-C/ngx-loading#71]
![ngx-loading_gallery](https://user-images.githubusercontent.com/13302305/44680280-47288480-aa0b-11e8-928a-4e39a1710b03.gif)

please feel free to include this image in your documentation, if you'd like

(one should point out, that you can get more striking effects if you change primaryColour and secondaryColour config properties)

**Comment by Zak-C** [comment]
Hi @Balagii,

Thank you very much for putting this together. 

I have recently released a new version of the library and used this post as inspiration for a demo, which is documented within the README.
