### ISSUE TITLE
Is it possible to change the primaryColour programatically from the component type script file

### ISSUE THREAD

**Issue by pradeep864** [Zak-C/ngx-loading#83]
### Sample Code
        LoadingModule.forRoot({
            animationType: ANIMATION_TYPES.threeBounce,
            backdropBackgroundColour: 'rgba(0,0,0,0.1)',
            backdropBorderRadius: '10px',
            fullScreenBackdrop: true,
            primaryColour: '#f0ad4e',
            secondaryColour: '#f0ad4e',
            tertiaryColour: '#f0ad4e'
        })

### Version
Angular version - 4
ngx-loading version - 1.0.8

**Comment by Zak-C** [comment]
Yes, please check the documentation / StackBlitz demo. You can pass configuration into each specific ngx-loading element, as well as providing the global styling.
