### ISSUE TITLE
fullScreenBackdrop:true is NOT working in IE browser

### ISSUE THREAD

**Issue by nikhildesu** [Zak-C/ngx-loading#84]
Angular 6 - My input form will be initially hidden and later when it is enabled, user needs to scroll down and click submit.  Upon clicking the button, the loader shows only on the top part of page  but not entire page. Tried using fullScreenBackdrop: true property but it is not working.  It works fine in other browsers but not in IE. Can anyone help on this ?

**Comment by kenan435** [comment]
@nikhildesu It does on release 1.0.14 At lease it does for me. I tried >1.0.14 and it seems broken.

**Comment by JonB16** [comment]
this is bullshit..... still broken
