### ISSUE TITLE
Loading Is not happening on Page which has Charts

### ISSUE THREAD

**Issue by sathyakps** [Zak-C/ngx-loading#85]
I Have used ngx-loading in my project which is working fine on normal page. When i try to use it on a page which has any charts , Loader is not Working. Please suggest the possible method. 

I am using Latest version of ngx-loading and ngx-echarts.

**Comment by crooksey** [comment]
Its quite possible the version of ngx-loading you are using simply has a higher z-index values. The default for this project is 1999, if the loading screen is below other elements, they probably use a higher value than this.
