### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by jeboersema** [Zak-C/ngx-loading#86]
Hi

When will Angular 7 be supported? I am looking to use the template functionality within Angular 7 but it does not seem to work.

Regards

**Comment by bradleyquinn** [comment]
Our implementation currently works with Angular 7, but NPM tells you that you have missing dependencies.  I agree,  however, it needs to be updated.

**Comment by pspkshah** [comment]
Your package.json file shows project is in 6.1 not in 7, can you please confirm its working for angular 7 ?
I have upgraded my project from angular 6 to 7.2 and its stoped working

**Comment by Zak-C** [comment]
This package now officially supports Angular 7. Please use version 7.0.0
