### ISSUE TITLE
Can we apply the overlay on one element only ? 

### ISSUE THREAD

**Issue by kevincaradant** [Zak-C/ngx-loading#9]
Hi

I tried to apply the overlay only on the <md-table> element. But it's seems that the overlay is on the  <md-card> only, so on the full card ? 

Do you know if it's possible or if that can be a feature to apply the overlay and loading only on one element HTML ? 

Thank you in advance

Regards

**Comment by Zak-C** [comment]
Hi, 

If you make whatever container you have position: relative, the backdrop will fill that container. 

Thanks

**Comment by kevincaradant** [comment]
ah yes, you're right, thank you  :)

I close this issue :)
