### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by igorlino** [Zak-C/ngx-loading#92]
Hi,

Following:
https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27

Using the default command to update to the latest version 8:

ng update @angular/cli @angular/core

there is an error:

Package "ngx-loading" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").
                  Package "ngx-loading" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").
Incompatible peer dependencies found. See above.

Thanks,
Igor

**Comment by obraeckman** [comment]
> Hi,
> 
> Following:
> https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27
> 
> Using the default command to update to the latest version 8:
> 
> ng update @angular/cli @angular/core
> 
> there is an error:
> 
> Package "ngx-loading" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").
> Package "ngx-loading" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").
> Incompatible peer dependencies found. See above.
> 
> Thanks,
> Igor

Confirmed... I have the same issue.

**Comment by chadbr** [comment]
same... @igorlino did you find a workaround?

**Comment by chadbr** [comment]
Looks like @Zak-C hasn't been on github this year... may be time to fork.
