### ISSUE TITLE
peer dependencies warnings 

### ISSUE THREAD

**Issue by omar-dulaimi** [Zak-C/ngx-loading#99]
Hello there, I'm receiving these warnings in my console:
```
npm WARN ngx-loading@3.0.1 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-loading@3.0.1 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

```
Even though I have @angular/core: "~8.2.0" && @angular/common: "~8.2.0" installed.

Any insights?
thank you

**Comment by Zak-C** [comment]
Please check out the README and use the correct version of the package for your needs. V7 and V8 were both recently released. I believe you will want to use V8.0.0.
